name: Python CI

on:
  schedule:
    - cron: '0 0 * * sun'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: ./python-client-sphinx
    - uses: actions/checkout@v2
      with:
        repository: appium/python-client
        path: ./python-client
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
      working-directory: python-client
    - name: Build doc
      shell: bash -xe {0}
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        bash generate.sh
      working-directory: python-client/docs
    - name: Check if PR needs to be created
      shell: bash -xe {0}
      run: |
        rm -r docs
        cp -r ../python-client/docs/_build/html ./docs
        # no_change == 0 -> Has changes, no_change == 1 -> No changes
        git --no-pager diff --stat
        no_change=`git --no-pager diff --stat | grep "2 files changed, 2 insertions(+), 2 deletions(-)" | wc -l | sed 's/ //'`
        echo "NO_CHANGE=$no_change" >> $GITHUB_ENV
      working-directory: python-client-sphinx
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        path: ./python-client-sphinx
        reviwers: KazuCocoa, mykola-mokhnach, ki4070ma
      if: ${{ env.NO_CHANGE == 0 }}
