name: Python CI

on:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: ./python-client-sphinx
    - uses: actions/checkout@v2
      with:
        repository: appium/python-client
        path: ./python-client
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Setup python-client
      run: |
        python -m pip install --upgrade pip
        python setup.py install
      working-directory: python-client
    - name: Build doc
      shell: bash -xe {0}
      run: |
        python -m pip install -r requirements.txt
        bash generate.sh
      working-directory: python-client/docs
    - name: Check if PR needed
      shell: bash -xe {0}
      run: |
        rm -r docs
        cp -r ../python-client/docs/_build/html ./docs
        git --no-pager diff --stat
        if [ -z "$(git --no-pager diff --stat -- . ':(exclude)docs/_sources/index.rst.txt')" ]; then git checkout .; fi
        if (git --no-pager diff --stat | grep -q "2 files changed, 2 insertions(+), 2 deletions(-)"); then exit 1; fi
      working-directory: python-client-sphinx
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        path: ./python-client-sphinx
